# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - arm_1_controller
    - gripper_controller
    - gripper_1_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    action_ns: follow_joint_trajectory
    default: true
  arm_1_controller:
    type: FollowJointTrajectory
    joints:
      - joint1_1
      - joint2_1
      - joint3_1
      - joint4_1
      - joint5_1
      - joint6_1
    action_ns: follow_joint_trajectory
    default: true
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - left_finger_joint
      - right_finger_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper_1_controller:
    type: FollowJointTrajectory
    joints:
      - left_finger_joint_1
      - right_finger_joint_1
    action_ns: follow_joint_trajectory
    default: true